learning bash

diff --git a/languages/bash/theory/operators b/languages/bash/theory/operators
--- a/languages/bash/theory/operators
+++ b/languages/bash/theory/operators
@@ -3,7 +3,7 @@
 Операторы в bash
 ==============================
 Арифметические операторы
-------------------------------
+==============================
 
 В Bash арифметика выполняется с помощью:
 
@@ -22,9 +22,9 @@
 ++	Инкремент	let a=5; echo $((a++)) → 6
 --	Декремент	let a=5; echo $((--a)) → 4
 
-------------------------------
+==============================
 Операторы сравнения
-------------------------------
+==============================
 
 Используются для проверки условий в конструкциях if, while и т.д.
 
@@ -59,14 +59,32 @@
 -r	Файл доступен для чтения
 -w	Файл доступен для записи
 -x	Файл доступен для выполнения
-------------------------------
+==============================
 Логические операторы
-------------------------------
-
+==============================
 Используются для комбинирования условий.
-
+------------------------------
 &&  Логическое И (AND) - выполняет следующую команду только в случае успешного завершения предыдущей команды.
+------------------------------
 ||  Логическое ИЛИ (OR) - выполняет следующую команду только в случае неуспешного завершения предыдущей команды. 
+
+Двоеточие (:) — это пустая инструкция, которая ничего не делает.
+
+if [[ -z "$DIR" ]]; then
+:
+else
+cd "$DIR"
+fi
+
+Правильнее написать:
+[[ -z "$DIR" ]] || cd "$DIR"
+
+Если требуется выполнить несколько команд после пары символов ||,
+как в ветке else, или после &&, как в ветке then, следует
+сгруппировать команды в одно предложение справа от && или ||, например:
+
+cd /tmp || { echo "cd to /tmp failed." ; exit ; }
+------------------------------
 !	Логическое НЕ (NOT)     [ ! -f "file.txt" ]
 
 ------------------------------
