learning bash

diff --git a/languages/bash/functions b/languages/bash/functions
--- a/languages/bash/functions
+++ b/languages/bash/functions
@@ -126,8 +126,105 @@ echo "Произошла ошибка: $@" >> debug.log
 }
 
 Менять что-либо в местах вызова функции не нужно.
+==============================
+Возврат результата функции
+==============================
+Чтобы вернуть результат функции, процедурные языки имеют встроенную команду. Обычно она называется return. В Bash эта команда тоже есть. Но её поведение отличается. Команда return в Bash не возвращает значение. Она передаёт код возврата, то есть целое число от 0 до 255.
+
+Полный алгоритм вызова и выполнения функции выглядит так:
+
+1. При выполнении команды встречается имя функции.
+2. Интерпретатор переходит в тело функции и исполняет его с первой команды.
+3. Если в теле функции встречается команда return, выполнение функции прекращается. Bash переходит в место её вызова. В специальный параметр $? записывается код возврата функции. Это параметр команды return.
+4. Если в теле функции нет return, Bash выполняет его до последней команды. После этого интерпретатор переходит в место вызова функции.
+
+В других процедурных языках команда return возвращает переменную любого типа: число, строку или массив. Такое же поведение можно получить и в Bash.
 ------------------------------
+Для этого есть три способа:
+------------------------------
+1. Подстановка команд.
+
+code_to_error()
+{
+    case $1 in
+      1)
+        echo "Не найден файл"
+        ;;
+      2)
+        echo "Нет прав для чтения файла"
+        ;;
+    esac
+}
+
+print_error()
+{
+    echo "$(code_to_error $1) $2" >> debug.log
+}
+
+Вызов функции code_to_error помещается в подстановку команды. Благодаря этому, Bash подставит в место вызова функции всё, что она выведет на консоль.
+------------------------------
+2. Глобальная переменная.
+
+Все глобальные переменные, через которые функции возвращают значения, имеют префикс знак подчёркивания _.
+
+code_to_error()
+{
+    case $1 in
+      1)
+        _error_text="Не найден файл"
+        ;;
+      2)
+        _error_text="Нет прав для чтения файла"
+        ;;
+    esac
+}
+
+print_error()
+{
+    code_to_error $1
+    echo "$_error_text $2" >> debug.log
+}
+
+Результат функции code_to_error записывается в переменную error_text. Затем значения параметра $2 и error_text подставляются в команду echo в функции print_error. Так получается сообщение для вывода в лог-файл.
 
 
+------------------------------
+3. Вызывающая сторона указывает глобальную переменную.
 
+Этот способ возврата значения из функции решает проблему конфликта имён.Вызывающая сторона задаёт имя глобальной переменной. Функция записывает свой результат в переменную с этим именем.
+
+Имя передаётся через параметр функции, как и любое другое значение. Дальше, функция использует команду eval. Эта команда конвертирует текст в Bash-команду. Имя переменной хранится в виде текста. Поэтому без eval обратиться к переменной не получится.
+
+
+code_to_error()
+{
+    local _result_variable=$2
+
+    case $1 in
+      1)
+        eval $_result_variable="'Не найден файл'"
+        ;;
+      2)
+        eval $_result_variable="'Нет прав для чтения файла'"
+        ;;
+    esac
+}
+
+print_error()
+{
+code_to_error $1 "error_text"
+    echo "$error_text $2" >> debug.log
+}
+==============================
+Область видимости переменных
+==============================
+Чтобы решить конфликт имён в Bash, ограничивайте область видимости переменных.
+
+Если объявить переменную с ключевым словом local, её область видимости ограничится телом функции. Другими словами, переменная будет доступна только в теле функции.
+
+В Bash область видимости локальной переменной ограничена временем исполнения функции, в которой она объявлена. Такая область видимости называется динамической. В современных языках чаще встречается лексическая область видимости. При этом подходе переменная доступна только в теле функции, но не за его пределами (например, в вызываемых функциях).
+
+Локальные переменные не попадают в глобальную область видимости. Это гарантирует, что никакая функция не перезапишет их случайно.
+
+Глобальная переменная становится недоступна в теле функции только после объявления локальной переменной с тем же именем.
 
